### ISSUE TITLE
代码公开

### ISSUE THREAD

**Issue by ghost** [Whileherham/IMR-HSNet#1]
很感谢你们的工作！请问代码什么时候会公开？谢谢！

**Comment by Whileherham** [comment]
感谢您的关注！现在正式代码正在走公司的开源流程，可能还需要一段时间才能公开。但是如果您需要的话，可以留下电子邮箱，我可以提前发送一份代码~

**Comment by ghost** [comment]
xinhao@njust.edu.cn  非常感谢！

**Comment by Whileherham** [comment]
已发送，请查收~

**Comment by Whileherham** [comment]
Hi，我发送邮件时，始终提示邮件被退回（哪怕我只发送链接都会被退回）。请参考这个下载链接吧https://cloud.tsinghua.edu.cn/d/a9161e30740143b4879a/。
由于正式代码的开源流程仍在进行，请不要公开这份代码，谢谢！

**Comment by ghost** [comment]
好的，谢谢！我只会用于个人科研。祝您生活愉快，科研顺利~




蔡鑫浩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Whileherham/IMR-HSNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月2日(星期三) 下午3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Whileherham/IMR-HSNet] 代码公开 (Issue #1)





 
Hi，我发送邮件时，始终提示邮件被退回（哪怕我只发送链接都会被退回）。请参考这个下载链接吧https://cloud.tsinghua.edu.cn/d/a9161e30740143b4879a/。
 由于正式代码的开源流程仍在进行，请不要公开这份代码，谢谢！

**Comment by sorrowyn** [comment]
非常有趣的工作。
如果条件允许，可以分享给我一份代码嘛？

**Comment by Whileherham** [comment]
感谢关注，在代码正式公开之前，您可以参考这个下载链接（下载链接有三天有效期） https://cloud.tsinghua.edu.cn/f/f9781af52c6941aa959f/

**Comment by sorrowyn** [comment]
> 感谢关注，在代码正式公开之前，您可以参考这个下载链接（下载链接有三天有效期） https://cloud.tsinghua.edu.cn/f/f9781af52c6941aa959f/

感谢的热心回复和帮助。
祝好！
